In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
data = pd.read_csv("heart_failure_clinical_records_dataset.csv")
data.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [54]:
data.describe()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
count,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.00000,299.000000,299.000000,299.00000,299.000000,299.00000
mean,60.833893,0.431438,581.839465,0.418060,38.083612,0.351171,263358.029264,1.39388,136.625418,0.648829,0.32107,130.260870,0.32107
std,11.894809,0.496107,970.287881,0.494067,11.834841,0.478136,97804.236869,1.03451,4.412477,0.478136,0.46767,77.614208,0.46767
min,40.000000,0.000000,23.000000,0.000000,14.000000,0.000000,25100.000000,0.50000,113.000000,0.000000,0.00000,4.000000,0.00000
25%,51.000000,0.000000,116.500000,0.000000,30.000000,0.000000,212500.000000,0.90000,134.000000,0.000000,0.00000,73.000000,0.00000
50%,60.000000,0.000000,250.000000,0.000000,38.000000,0.000000,262000.000000,1.10000,137.000000,1.000000,0.00000,115.000000,0.00000
75%,70.000000,1.000000,582.000000,1.000000,45.000000,1.000000,303500.000000,1.40000,140.000000,1.000000,1.00000,203.000000,1.00000
max,95.000000,1.000000,7861.000000,1.000000,80.000000,1.000000,850000.000000,9.40000,148.000000,1.000000,1.00000,285.000000,1.00000

In [55]:
target_variable = "serum_sodium"

X = data.drop(target_variable, axis=1)
display(X)

y =data[target_variable]
y

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,0,0,8,1
...,...,...,...,...,...,...,...,...,...,...,...,...
294,62.0,0,61,1,38,1,155000.00,1.1,1,1,270,0
295,55.0,0,1820,0,38,0,270000.00,1.2,0,0,271,0
296,45.0,0,2060,1,60,0,742000.00,0.8,0,0,278,0
297,45.0,0,2413,0,38,0,140000.00,1.4,1,1,280,0
298,50.0,0,196,0,45,0,395000.00,1.6,1,1,285,0

0      130
1      136
2      129
3      137
4      116
      ...
294    143
295    139
296    138
297    140
298    136
Name: serum_sodium, Length: 299, dtype: int64

In [56]:
X.columns

Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
       'ejection_fraction', 'high_blood_pressure', 'platelets',
       'serum_creatinine', 'sex', 'smoking', 'time', 'DEATH_EVENT'],
      dtype='object')

In [57]:
## homework: use the USer Id and check the differences of the performances

numeric_features = ['age', 'creatinine_phosphokinase','ejection_fraction','serum_creatinine','serum_sodium','time']

categorical_features = ["anaemia",'diabetes','high_blood_pressure','sex','smoking','DEATH_EVENT']

In [58]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state =42)

In [59]:
y.value_counts()/len(y)

136    0.133779
137    0.127090
140    0.117057
134    0.107023
138    0.076923
139    0.073579
135    0.053512
132    0.046823
141    0.040134
142    0.036789
133    0.033445
145    0.030100
130    0.030100
144    0.016722
131    0.016722
127    0.010033
143    0.010033
128    0.006689
129    0.006689
121    0.003344
116    0.003344
146    0.003344
126    0.003344
124    0.003344
113    0.003344
125    0.003344
148    0.003344
Name: serum_sodium, dtype: float64

In [60]:
y_train.value_counts()/len(y_train)

136    0.138393
137    0.129464
140    0.120536
134    0.111607
138    0.080357
139    0.066964
132    0.049107
141    0.049107
135    0.044643
133    0.035714
142    0.031250
130    0.022321
145    0.022321
144    0.017857
131    0.017857
143    0.008929
128    0.008929
129    0.008929
127    0.008929
113    0.004464
116    0.004464
125    0.004464
126    0.004464
121    0.004464
146    0.004464
Name: serum_sodium, dtype: float64

In [61]:
y_test.value_counts()/len(y_test)

136    0.120000
137    0.120000
140    0.106667
139    0.093333
134    0.093333
135    0.080000
138    0.066667
145    0.053333
142    0.053333
130    0.053333
132    0.040000
133    0.026667
143    0.013333
148    0.013333
127    0.013333
131    0.013333
141    0.013333
144    0.013333
124    0.013333
Name: serum_sodium, dtype: float64

In [62]:
X_train.isna().sum()

age                         0
anaemia                     0
creatinine_phosphokinase    0
diabetes                    0
ejection_fraction           0
high_blood_pressure         0
platelets                   0
serum_creatinine            0
sex                         0
smoking                     0
time                        0
DEATH_EVENT                 0
dtype: int64

In [63]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

numeric_transformer = Pipeline(steps = [("imputer", SimpleImputer(strategy="mean")),
                                       ("scaler", StandardScaler())
                                       ])

In [64]:
from sklearn.preprocessing import OneHotEncoder
categorical_transformer = OneHotEncoder(drop = "first") # same in dummification

In [65]:
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(
            transformers = [("numerical", numeric_transformer, numeric_features), 
                            ("categorical", categorical_transformer, categorical_features)]
)

In [66]:
from sklearn.linear_model import LogisticRegression
# Instantiate and fit a logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)

/Users/bernardferreiraduodu/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [67]:
# Make predictions
y_pred = model.predict(X_test)

In [73]:
# Define and train a classifier (Random Forest Classifier in this example)
classifier = RandomForestClassifier(random_state=42)
classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [74]:
## predictions

pred_train = classifier.predict(X_train)
display(pred_train)

pred_test = classifier.predict(X_test)
display(pred_test)

array([125, 131, 136, 138, 130, 136, 121, 136, 140, 136, 137, 132, 136,
       131, 136, 138, 142, 139, 145, 140, 134, 140, 132, 140, 137, 135,
       132, 145, 134, 134, 126, 140, 140, 134, 135, 139, 137, 138, 141,
       134, 134, 138, 134, 137, 132, 137, 136, 136, 130, 143, 137, 135,
       142, 134, 136, 136, 141, 138, 128, 140, 145, 135, 129, 139, 140,
       138, 135, 141, 135, 137, 134, 132, 133, 133, 138, 132, 137, 139,
       143, 127, 127, 137, 140, 140, 139, 137, 134, 134, 132, 134, 136,
       138, 139, 141, 141, 134, 136, 144, 134, 137, 138, 140, 140, 134,
       130, 140, 134, 141, 135, 132, 140, 137, 134, 131, 135, 137, 137,
       139, 140, 139, 134, 136, 136, 116, 140, 128, 138, 137, 132, 139,
       136, 139, 137, 136, 144, 138, 140, 140, 137, 142, 137, 136, 134,
       145, 137, 141, 137, 135, 138, 132, 137, 136, 138, 142, 136, 141,
       141, 113, 138, 138, 142, 129, 140, 133, 136, 139, 134, 137, 141,
       134, 134, 130, 137, 138, 134, 145, 136, 131, 140, 140, 142, 136,
       136, 140, 133, 146, 136, 137, 139, 133, 136, 137, 140, 141, 132,
       138, 137, 140, 140, 144, 133, 136, 133, 137, 133, 136, 134, 142,
       135, 139, 136, 138, 139, 140, 140, 134, 136, 136, 137, 136, 139,
       137, 130, 144])

array([134, 140, 136, 131, 139, 141, 136, 136, 132, 139, 137, 134, 136,
       136, 137, 136, 136, 137, 140, 137, 136, 135, 134, 138, 136, 140,
       136, 137, 136, 137, 137, 137, 136, 134, 134, 138, 138, 134, 136,
       137, 140, 132, 137, 140, 136, 136, 136, 136, 139, 137, 134, 140,
       136, 140, 141, 136, 137, 136, 134, 136, 129, 134, 136, 141, 134,
       140, 133, 134, 134, 136, 136, 134, 137, 136, 137])

In [75]:
y_train

225    125
78     131
66     136
296    138
192    130
      ...
188    136
71     139
106    137
270    130
102    144
Name: serum_sodium, Length: 224, dtype: int64

In [81]:
prob_train = classifier.predict_proba(X_train)

display(prob_train)

prob_test = classifier.predict_proba(X_test)
display(prob_test)

array([[0.  , 0.  , 0.  , ..., 0.01, 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.01, 0.  , 0.  ],
       [0.  , 0.04, 0.  , ..., 0.01, 0.  , 0.  ],
       ...,
       [0.  , 0.  , 0.  , ..., 0.01, 0.  , 0.  ],
       [0.03, 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.77, 0.01, 0.  ]])

array([[0.01, 0.  , 0.04, ..., 0.01, 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.05, 0.  , 0.  ],
       [0.  , 0.  , 0.02, ..., 0.07, 0.01, 0.  ],
       ...,
       [0.01, 0.  , 0.  , ..., 0.01, 0.02, 0.  ],
       [0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , ..., 0.02, 0.04, 0.  ]])

In [77]:
# Make predictions on the test set
y_pred = model.predict(X_test)